from .home import *
from .ajax import *
from .importfiles import *
from .assigntest import *
from .assignments import *
from .meetings import *
from .users import *
from .profile import *
from .reports import *