# Generated by Django 4.0.3 on 2022-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='nde_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
