# Generated by Django 4.0.3 on 2022-03-31 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_meeting_meeting_id_remove_notes_note_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
