# Generated by Django 4.0.3 on 2022-03-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_meeting_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='notes',
        ),
    ]
