# Generated by Django 4.0.3 on 2022-03-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='tid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='type',
            field=models.TextField(choices=[('M', 'Mentor'), ('S', 'School'), ('C', 'Classroom'), ('P', 'Student')], default='', max_length=1),
        ),
    ]
